### ISSUE TITLE
"Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by alexlrobertson** [BohdanTkachenko/webpack-split-by-path#35]
I'm encountering an error when using this plugin with the Webpack@4 beta.

```
TypeError: Cannot read property 'bind' of undefined
    at /Users/alexlrobertson/Sites/project/node_modules/webpack-split-by-path/index.js:87:35
    at SyncBailHook.eval (eval at create (/Users/alexlrobertson/Sites/project/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:12:16)
    at SyncBailHook.lazyCompileHook [as _call] (/Users/alexlrobertson/Sites/project/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/alexlrobertson/Sites/project/node_modules/webpack/lib/Compilation.js:785:30)
    at hooks.make.callAsync.err (/Users/alexlrobertson/Sites/project/node_modules/webpack/lib/Compiler.js:439:17)
    at _err0 (eval at create (/Users/alexlrobertson/Sites/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/alexlrobertson/Sites/project/node_modules/webpack/lib/Compilation.js:672:11)
    at processModuleDependencies.err (/Users/alexlrobertson/Sites/project/node_modules/webpack/lib/Compilation.js:614:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"
```

**Comment by MichalWadowski** [comment]
I confirm this issue for webpack@"4.0.1"

**Comment by LeoIannacone** [comment]
Hi, any updates on this ?

**Comment by finom** [comment]
Ping
